Add possibility for setting monaco editor options
joeskeen/reveal-monaco pull request #2
Opened 2023-12-07 14:15 UTC by elsvene

I suggest to add an additional configuration setting (in the code change I called it 'editorOptions') that allows passing monaco editor options (such as hiding the minimap, enabling word wrap) as per [https://microsoft.github.io/monaco-editor/typedoc/variables/editor.EditorOptions.html](https://microsoft.github.io/monaco-editor/typedoc/variables/editor.EditorOptions.html).

I also extended the documentation correspondingly.

Attached you find a small reveal test case:
[index.html.zip](https://github.com/joeskeen/reveal-monaco/files/13601120/index.html.zip)

2023-12-08 16:45 UTC, joeskeen requested changes

2023-12-08 16:45 UTC, joeskeen commented on plugin.js
> +          ...this.options.editorOptions
I think the spread should probably go first, as they are the globally configured options, which should be overwritten by `value` and `language` on the specific instance if provided. Other than that, this looks awesome! Thanks for contributing!

2023-12-09 12:53 UTC, elsvene commented
You are right, I moved the spread to go first!

2023-12-09 17:42 UTC, joeskeen approved these changes

2023-12-09 17:42 UTC, merged